version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
    - post_db:/data/db
    networks:
    - back_net
  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
    - ${UI_PORT}:9292/tcp
    networks:
    - front_net
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
    - back_net
    - front_net
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
    - back_net
    - front_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
    - '9090:9090'
    volumes:
    - prometheus_data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention=1d'

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
