version: '3.3'

services:
  post_db:
    image: mongo:3.2
    volumes:
    - post_db:/data/db
    networks:
    - back_net

  ui:
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
    - ${UI_PORT}:9292/tcp
    networks:
    - front_net

  post:
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
    - back_net
    - front_net

  comment:
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
    - back_net
    - front_net

  logging:
    driver: "fluentd"
    options:
      fluentd-address: localhost:24224
      tag: service.post

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
