---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      name: comment-deployment
      labels:
        app: comment
    spec:
      containers:
      - image: danniilperestoronin/comment:logging
        name: comment
        env:
        - name: COMMENT_DATABASE_HOST
          value: mongo.default.svc.cluster.local
