---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      name: post
      labels:
        app: post
    spec:
      containers:
      - image: danniilperestoronin/post:logging
        name: post
        env:
        - name: POST_DATABASE_HOST
          value: mongo.default.svc.cluster.local
        ports:
        - containerPort: 5000
